MOHON DI PAHAMI DAHULU YA KAK..!!!
(www.eydcom.com)
 
1. PRODUK SOURCE CODE MEMANG TIDAK DI SERTAKAN TUTORIAL NYA
2. JADI PASTIKAN KAKAK MEMANG SUDAH PAHAM DENGAN XAMPP, CPANEL, DAN SOURCE CODE
 
===================================
Website offline yang dibangun melalui XAMPP dapat dijadikan online dengan cara upload web hosting di cPanel. 
www.eydcom.com

==================================
PENTING :

Silahkan di ekstrak dan dibaca dulu file txt nya di folder database dan source code

Jika dijalankan localhost atau offline diwajibkan install XAMPP dulu sebagai server localhost nya link ada di file txt folder database
*WAJIB MENGGUNAKAN XAMPP YG KITA REKOMENDASI KAN & LINK DOWNLOAD DI FILE TXT FOLDER DATABASE*

Untuk dijadikan online atau upload ke hosting jangan gunakan hosting & domain yg gratisan

*Provider Hosting yang kita sarankan:*
1. GapuraHoster = https://gapurahoster.co.id/member/aff.php?aff=1498
2. DewaWeb = https://www.dewaweb.com/aff.php?aff=28556
3. NiagaHoster = https://niagahoster.co.id?REFERRALCODE=1EYD316
4. IdWebHost = https://idwebhost.com/aff/9678
5. DomaiNesia = https://my.domainesia.com/ref.php?u=23355
-----------------------------------
Pengiriman source code hanya 1x 

Hal yg berhubungan dengan hilangnya file source code yg sudah dikirim bukan tanggung jawab kita

Warning
Kita hanya menyarankan produk kita digunakan untuk:
1. Membantu Bisnis Anda 
2. Tugas kuliah
3. Projek klien Anda

NB: Jika dijalankan localhost lancar dan pastinya di hosting juga lancar jika diupload ke hosting & domain berbayar, kita tidak menyarankan program kita diupload ke hosting gratisan.
www.eydcom.com
-----------------------------------
Terimakasih telah Order di EYD COMPUTER

Info selengkanya bisa dilihat disini:
www.eydcom.com

